using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace WorldWideSports
{
    public partial class CreateAccount : Form
    {
        public CreateAccount()
        {
            InitializeComponent();
        }

        private void usersBindingNavigatorSaveItem_Click(object sender, EventArgs e)
        {
            // this code is generated by the designer and is used to save changes to the database.
            // It is not called in this form, but it is required for the designer to work properly.
            // It can be left empty or removed if desired.
            this.Validate();
            this.usersBindingSource.EndEdit();
            this.tableAdapterManager.UpdateAll(this.worldWideSportsDBDataSet);

        }

        private void CreateAccount_Load(object sender, EventArgs e)
        {
            // TODO: This line of code loads data into the 'worldWideSportsDBDataSet.Users' table. You can move, or remove it, as needed.
            this.usersTableAdapter.Fill(this.worldWideSportsDBDataSet.Users);

            //center the panel on the form
            CenterPanel();
        }

        private void createAccountBtn_Click(object sender, EventArgs e)
        {
            //get the username from the text box
            string username = usernameTxtBox.Text;
            string password = passwordTxtBox.Text;
            string confirmPassword = confirmPasswordTxtBox.Text;

            //check and make sure the username is not empty and the password is not empty and the confirm password is not empty
            if(username == "" || password == "" || confirmPassword == "")
            {
                MessageBox.Show("Please fill in all fields.");
                return;
            }

            //validate the username and password
            if (password != confirmPassword)
            {
                // if the password and confirm password do not match, show an error message and clear the password fields
                MessageBox.Show("Passwords do not match. Please try again.");

                //clear the password fields and set focus back to the password text box
                passwordTxtBox.Clear();

                //clear the confirm password text box as well
                confirmPasswordTxtBox.Clear();

                //set focus back to the password text box
                passwordTxtBox.Focus();

                //exit the method so the user can try again
                return;
            }

            //Username already exists
            int existingCount = (int)usersTableAdapter.CheckUsername(username);
            if (existingCount > 0)
            {
                // if the username already exists, show an error message and set focus back to the username text box
                MessageBox.Show("Username already exists. Please choose a different username.");

                //clear the username text box and set focus back to it
                usernameTxtBox.Focus();

                //exit the method so the user can try again
                return;
            }

            //validate the password strength
            string error; //holds the error string
            if (!IsStrongPassword(password, out error))
            {
                // if the password is not strong, show the error message and clear the password fields
                MessageBox.Show(error);

                //clear the password fields and set focus back to the password text box
                passwordTxtBox.Clear();

                //clear the confirm password text box as well
                confirmPasswordTxtBox.Clear();

                //set focus back to the password text box
                passwordTxtBox.Focus();

                //exit the method so the user can try again
                return;
            }

            //Insert user
            try
            {
                usersTableAdapter.CreateUser(username, password); // password stored in PasswordHash column (plain text for class)

                // if the account was created successfully, show a success message and close the form
                MessageBox.Show("Account created!");

                //close the form to return to the login screen
                this.Close();
            }
            catch (Exception ex)
            {
                // if there was an error creating the account, show an error message
                MessageBox.Show("Create account failed: " + ex.Message);
            }
        }

        //validate the password
        private bool IsStrongPassword(string password, out string error)
        {
            //error is empty to have a place holder
            error = "";

            // A strong password must be at least 8 characters long and contain at least one uppercase letter, one lowercase letter, one number, and one special character
            bool hasUpper = false;
            bool hasLower = false;
            bool hasDigit = false;
            bool hasSpecial = false;
            string specials = "!@#$%^&*()_+=-[]{}|\\;:'\",.<>/?";

            if (password.Length < 8)
            {
                error = "Password must be at least 8 characters long.";
                return false;
            }

            //foreach checks if password has uppercase letter, lowercase letter, number, or special character and set the corresponding boolean variable to true if it is
            foreach (char c in password)
            {
                if (char.IsUpper(c))
                {
                    hasUpper = true;
                }
                else if (char.IsLower(c))
                {
                    hasLower = true;
                }
                else if (char.IsDigit(c))
                {
                    hasDigit = true;
                }
                else if (specials.Contains(c))
                {
                    hasSpecial = true;
                }
            }

            // check the results after the loop is finished
            if (!hasUpper)
            {
                error = "Password must contain at least one uppercase letter.";
                return false;
            }
            if (!hasLower)
            {
                error = "Password must contain at least one lowercase letter.";
                return false;
            }
            if (!hasDigit)
            {
                error = "Password must contain at least one number.";
                return false;
            }
            if (!hasSpecial)
            {
                error = "Password must contain at least one special character.";
                return false;
            }

            // return true if the password is strong
            return true;
        }

        private void CenterPanel()
        {
            //center the panel on the form
            panel2.Left = (this.ClientSize.Width - panel2.Width) / 2;
            panel2.Top = (this.ClientSize.Height - panel2.Height) / 2;
        }
    }
}
